In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
Titanic=sns.load_dataset('titanic')
Titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [3]:
Titanic=pd.get_dummies(Titanic,drop_first=True)
Titanic

survived  pclass   age  sibsp  parch     fare  adult_male  alone  \
0           0       3  22.0      1      0   7.2500        True  False   
1           1       1  38.0      1      0  71.2833       False  False   
2           1       3  26.0      0      0   7.9250       False   True   
3           1       1  35.0      1      0  53.1000       False  False   
4           0       3  35.0      0      0   8.0500        True   True   
..        ...     ...   ...    ...    ...      ...         ...    ...   
886         0       2  27.0      0      0  13.0000        True   True   
887         1       1  19.0      0      0  30.0000       False   True   
888         0       3   NaN      1      2  23.4500       False  False   
889         1       1  26.0      0      0  30.0000        True   True   
890         0       3  32.0      0      0   7.7500        True   True   

     sex_male  embarked_Q  ...  who_woman  deck_B  deck_C  deck_D  deck_E  \
0           1           0  ...          0       0       0       0       0   
1           0           0  ...          1       0       1       0       0   
2           0           0  ...          1       0       0       0       0   
3           0           0  ...          1       0       1       0       0   
4           1           0  ...          0       0       0       0       0   
..        ...         ...  ...        ...     ...     ...     ...     ...   
886         1           0  ...          0       0       0       0       0   
887         0           0  ...          1       1       0       0       0   
888         0           0  ...          1       0       0       0       0   
889         1           0  ...          0       0       1       0       0   
890         1           1  ...          0       0       0       0       0   

     deck_F  deck_G  embark_town_Queenstown  embark_town_Southampton  \
0         0       0                       0                        1   
1         0       0                       0                        0   
2         0       0                       0                        1   
3         0       0                       0                        1   
4         0       0                       0                        1   
..      ...     ...                     ...                      ...   
886       0       0                       0                        1   
887       0       0                       0                        1   
888       0       0                       0                        1   
889       0       0                       0                        0   
890       0       0                       1                        0   

     alive_yes  
0            0  
1            1  
2            1  
3            1  
4            0  
..         ...  
886          0  
887          1  
888          0  
889          1  
890          0  

[891 rows x 24 columns]

In [4]:
Titanic.dropna(inplace=True)
Titanic

survived  pclass   age  sibsp  parch     fare  adult_male  alone  \
0           0       3  22.0      1      0   7.2500        True  False   
1           1       1  38.0      1      0  71.2833       False  False   
2           1       3  26.0      0      0   7.9250       False   True   
3           1       1  35.0      1      0  53.1000       False  False   
4           0       3  35.0      0      0   8.0500        True   True   
..        ...     ...   ...    ...    ...      ...         ...    ...   
885         0       3  39.0      0      5  29.1250       False  False   
886         0       2  27.0      0      0  13.0000        True   True   
887         1       1  19.0      0      0  30.0000       False   True   
889         1       1  26.0      0      0  30.0000        True   True   
890         0       3  32.0      0      0   7.7500        True   True   

     sex_male  embarked_Q  ...  who_woman  deck_B  deck_C  deck_D  deck_E  \
0           1           0  ...          0       0       0       0       0   
1           0           0  ...          1       0       1       0       0   
2           0           0  ...          1       0       0       0       0   
3           0           0  ...          1       0       1       0       0   
4           1           0  ...          0       0       0       0       0   
..        ...         ...  ...        ...     ...     ...     ...     ...   
885         0           1  ...          1       0       0       0       0   
886         1           0  ...          0       0       0       0       0   
887         0           0  ...          1       1       0       0       0   
889         1           0  ...          0       0       1       0       0   
890         1           1  ...          0       0       0       0       0   

     deck_F  deck_G  embark_town_Queenstown  embark_town_Southampton  \
0         0       0                       0                        1   
1         0       0                       0                        0   
2         0       0                       0                        1   
3         0       0                       0                        1   
4         0       0                       0                        1   
..      ...     ...                     ...                      ...   
885       0       0                       1                        0   
886       0       0                       0                        1   
887       0       0                       0                        1   
889       0       0                       0                        0   
890       0       0                       1                        0   

     alive_yes  
0            0  
1            1  
2            1  
3            1  
4            0  
..         ...  
885          0  
886          0  
887          1  
889          1  
890          0  

[714 rows x 24 columns]

### Scaling Methods

#### MinMax Scaler

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
minmax=MinMaxScaler()

In [7]:
x=Titanic[['age']]
x

age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
885  39.0
886  27.0
887  19.0
889  26.0
890  32.0

[714 rows x 1 columns]

In [9]:
x_transformed= minmax.fit_transform(x)
x_transformed

array([[0.27117366],
       [0.4722292 ],
       [0.32143755],
       [0.43453129],
       [0.43453129],
       [0.67328474],
       [0.01985423],
       [0.33400352],
       [0.17064589],
       [0.04498618],
       [0.72354863],
       [0.24604172],
       [0.48479517],
       [0.17064589],
       [0.68585072],
       [0.01985423],
       [0.3842674 ],
       [0.43453129],
       [0.42196532],
       [0.18321186],
       [0.34656949],
       [0.09525006],
       [0.4722292 ],
       [0.23347575],
       [0.49736115],
       [0.8240764 ],
       [0.34656949],
       [0.52249309],
       [0.25860769],
       [0.22090978],
       [0.17064589],
       [0.49736115],
       [0.33400352],
       [0.03242021],
       [0.23347575],
       [0.22090978],
       [0.08268409],
       [0.25860769],
       [0.61045489],
       [0.35913546],
       [0.81151043],
       [0.25860769],
       [0.35285248],
       [0.05755215],
       [0.13294798],
       [0.27117366],
       [0.4722292 ],
       [0.560

### Standard Scaler

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc= StandardScaler()

In [13]:
x_fare=Titanic[['fare']].values
x_fare

array([[  7.25  ],
       [ 71.2833],
       [  7.925 ],
       [ 53.1   ],
       [  8.05  ],
       [ 51.8625],
       [ 21.075 ],
       [ 11.1333],
       [ 30.0708],
       [ 16.7   ],
       [ 26.55  ],
       [  8.05  ],
       [ 31.275 ],
       [  7.8542],
       [ 16.    ],
       [ 29.125 ],
       [ 18.    ],
       [ 26.    ],
       [ 13.    ],
       [  8.0292],
       [ 35.5   ],
       [ 21.075 ],
       [ 31.3875],
       [263.    ],
       [ 27.7208],
       [ 10.5   ],
       [ 82.1708],
       [ 52.    ],
       [  8.05  ],
       [ 18.    ],
       [ 11.2417],
       [  9.475 ],
       [ 21.    ],
       [ 41.5792],
       [  7.8792],
       [ 17.8   ],
       [ 39.6875],
       [  7.8   ],
       [ 76.7292],
       [ 26.    ],
       [ 61.9792],
       [ 10.5   ],
       [  7.2292],
       [ 27.75  ],
       [ 46.9   ],
       [  7.2292],
       [ 80.    ],
       [ 83.475 ],
       [ 27.9   ],
       [ 10.5   ],
       [  8.1583],
       [  7.925 ],
       [  8.

In [15]:
x_fare_transformed=sc.fit_transform(x_fare)
x_fare_transformed

array([[-5.18977865e-01],
       [ 6.91896750e-01],
       [-5.06213563e-01],
       [ 3.48049152e-01],
       [-5.03849804e-01],
       [ 3.24647932e-01],
       [-2.57546055e-01],
       [-4.45544364e-01],
       [-8.74347866e-02],
       [-3.40277640e-01],
       [-1.54013385e-01],
       [-5.03849804e-01],
       [-6.46632722e-02],
       [-5.07552397e-01],
       [-3.53514694e-01],
       [-1.05319937e-01],
       [-3.15694541e-01],
       [-1.64413927e-01],
       [-4.10244924e-01],
       [-5.04243133e-01],
       [ 1.52318019e-02],
       [-2.57546055e-01],
       [-6.25358885e-02],
       [ 4.31727425e+00],
       [-1.31873467e-01],
       [-4.57520116e-01],
       [ 8.97780210e-01],
       [ 3.27248068e-01],
       [-5.03849804e-01],
       [-3.15694541e-01],
       [-4.43494512e-01],
       [-4.76902945e-01],
       [-2.58964310e-01],
       [ 1.30189940e-01],
       [-5.07079645e-01],
       [-3.19476556e-01],
       [ 9.44177482e-02],
       [-5.08577323e-01],
       [ 7.9